import json
from pathlib import Path
path = Path('work/notebooks/w03_data_contract.ipynb')
nb = json.loads(path.read_text())
nb['cells'][0]['source'] = [
    'import pandas as pd\n',
    '\n',
    'df = pd.read_csv("data/raw/content_refresh_anonymized.csv")\n',
    'window_cols = [c for c in df.columns if any(w in c for w in ("_90d", "_last_30d", "_prev_30d"))]\n',
    '\n',
    'print("rows", len(df))\n',
    'print("unique content_id", df["content_id"].nunique())\n',
    'print("duplicate content_id", df["content_id"].duplicated().sum())\n',
    'print("unique client_id", df["client_id"].nunique())\n',
    'print("date-like columns", [c for c in df.columns if "date" in c.lower()])\n',
    'print("window columns count", len(window_cols))\n',
    'print("window columns sample", sorted(window_cols)[:20])\n',
    'print("trend field missing values", df[["trend_direction", "trend_pct"]].isna().sum().to_dict())\n',
]
nb['cells'][1]['source'] = [
    'import pandas as pd\n',
    '\n',
    'df = pd.read_csv("data/raw/content_refresh_anonymized.csv")\n',
    '\n',
    'feature_fields = [\n',
    '    "search_volume", "competition", "competition_level", "cpc",\n',
    '    "content_type", "main_intent", "word_count", "char_count",\n',
    '    "provider_used", "model_used",\n',
    '    "impressions_90d", "clicks_90d", "pageviews_90d", "sessions_90d",\n',
    '    "users_90d", "engaged_sessions_90d", "ai_sessions_90d",\n',
    '    "scroll_events_90d", "days_with_impressions", "days_with_sessions",\n',
    '    "impressions_last_30d", "clicks_last_30d", "sessions_last_30d",\n',
    '    "impressions_prev_30d", "clicks_prev_30d", "sessions_prev_30d",\n',
    '    "content_age_days", "age_tier", "age_tier_order", "days_since_last_update",\n',
    '    "freshness_tier", "word_count_tier", "char_count_tier",\n',
    '    "ctr", "avg_position", "engagement_rate", "scroll_rate",\n',
    '    "ai_traffic_pct", "impression_tier", "position_tier",\n',
    '    "trend_pct"\n',
    ']\n',
    'label_fields = ["trend_direction", "trend_pct"]\n',
    'context_fields = ["content_id", "client_id"]\n',
    'excluded_fields = ["content_id", "client_id"]\n',
    '\n',
    'for name, fields in [\n',
    '    ("features", feature_fields),\n',
    '    ("label", label_fields),\n',
    '    ("context", context_fields),\n',
    '    ("excluded", excluded_fields),\n',
    ']:\n',
    '    present = [c for c in fields if c in df.columns]\n',
    '    missing = [c for c in fields if c not in df.columns]\n',
    '    print(f"{name}: present={len(present)}, missing={missing}")\n',
    '\n',
    'print("\\nlabel missing values")\n',
    'print(df[label_fields].isna().sum().to_dict())\n',
    'print("\\ncontext uniqueness")\n',
    'print(df[context_fields].nunique())\n',
    'print("duplicate content_id rows", df["content_id"].duplicated().sum())\n',
]
nb['cells'][2]['source'] = [
    'import pandas as pd\n',
    '\n',
    'df = pd.read_csv("data/raw/content_refresh_anonymized.csv")\n',
    '\n',
    'print("rows", len(df))\n',
    'print("unique content_id", df["content_id"].nunique())\n',
    'print("duplicate content_id", df["content_id"].duplicated().sum())\n',
    'print("unique client_id", df["client_id"].nunique())\n',
    'print("date-like columns", [c for c in df.columns if "date" in c.lower()])\n',
    'window_cols = [c for c in df.columns if any(w in c for w in ("_90d", "_last_30d", "_prev_30d"))]\n',
    'print("window columns count", len(window_cols))\n',
    'print("window columns sample", sorted(window_cols)[:30])\n',
    'print("\\ntrend_direction distribution")\n',
    'print(df["trend_direction"].value_counts(dropna=False).to_string())\n',
    'print("\\ntrend_pct summary")\n',
    'print(df["trend_pct"].describe().to_string())\n',
    'print("\\nmissing values for trend fields")\n',
    'print(df[["trend_direction", "trend_pct"]].isna().sum().to_dict())\n',
]
nb['cells'][3]['source'] = [
    'import pandas as pd\n',
    '\n',
    'df = pd.read_csv("data/raw/content_refresh_anonymized.csv")\n',
    '\n',
    'print("date-like columns", [c for c in df.columns if "date" in c.lower()])\n',
    'print("total rows", len(df))\n',
    'print("unique content_id", df["content_id"].nunique())\n',
    'print("duplicate content_id", df["content_id"].duplicated().sum())\n',
    'print("trend_direction unique", df["trend_direction"].nunique())\n',
    'print("trend_pct min/max", df["trend_pct"].min(), df["trend_pct"].max())\n',
    'print("\\nexample snapshot rows")\n',
    'print(df[["content_id", "impressions_90d", "clicks_90d", "sessions_90d", "trend_direction", "trend_pct"]].head(5).to_string(index=False))\n',
]
path.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
print('w03 notebook repaired')
